version: "3"
services:
  app:
    container_name: coco-service
    restart: on-failure
    build: ./
    ports:
      - "3100:3100"
    volumes:
      - .:/app
    command: npm run docker
networks:
  default:
    external:
      name: micro_poc